projects:
  app:
    schemaPath: packages/prisma/prisma.graphql
    extensions:
      endpoints:
        default: http://10.142.0.6:4466/trump-said-wtf/
  database:
    schemaPath: packages/prisma/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
