language: node_js
before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn -y
node_js:
  - 8
install:
  - yarn
script:
  - yarn run build-prod
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    update: true
