steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/worker:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/client:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/app',
        '--cache-from',
        'gcr.io/$PROJECT_ID/app',
        '-f',
        './server-slim.dockerfile',
        '.',
      ]
    timeout: 600s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/worker',
        '--cache-from',
        'gcr.io/$PROJECT_ID/worker',
        '-f',
        './worker.dockerfile',
        '.',
      ]
    timeout: 600s
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/client',
        '--cache-from',
        'gcr.io/$PROJECT_ID/client',
        './packages/client',
      ]
    timeout: 900s
  - name: 'gcr.io/$PROJECT_ID/client'
    args: ['run', 'bash -c cat dist.tar.gz > dist.tar.gz']
timeout: 2100s
images:
  - gcr.io/$PROJECT_ID/worker:latest
  - gcr.io/$PROJECT_ID/app:latest
  - gcr.io/$PROJECT_ID/client:latest
artifacts:
  objects:
    location: 'gs://ts-static-prod/'
    paths: ['dist.tar.gz']
