steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/app',
        '--cache-from',
        'gcr.io/$PROJECT_ID/app',
        '-f',
        './server-slim.dockerfile',
        '.',
      ]
    timeout: 600s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app:latest']
    timeout: 600s
timeout: 2100s
images:
  - gcr.io/$PROJECT_ID/app:latest
