runtime: custom
env: flex
service: worker
network:
  name: ts-network
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 30
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
