#cloudbuild.yaml
steps:
- name: ‘docker/compose:1.19.0’
  args: [‘up’, ‘-d’]
  secretEnv: ['PRISMA_MANAGEMENT_API_SECRET', 'PRISMA_SECRET', 'MYSQL_PASSWORD', 'MYSQL_USER']
  env: ['PRISMA_STAGE=production', 'CLOUDSQL_CONNECTION=summer-artwork-138223:us-east1:ts-prod', 'PRISMA_ENDPOINT=http://10.142.0.6:4466/trump-said-wtf/']

secrets:
- kmsKeyName: projects/summer-artwork-138223/locations/global/keyRings/ts-wtf/cryptoKeys/env
  secretEnv:
    PRISMA_MANAGEMENT_API_SECRET: CiQA4As1q7YQOSxKgypbeUX+oWGl6vReZR6qOjXolgmhoAvyddkSQwASR2PRA1zEBhFMXnbNEGtzh+DnTOFtQgQYGknYnU6UuSgbkPkcSp8XDEuq8knMwkOyQjxxca3JxFk7Y/PZZ6n6UcA=
    PRISMA_SECRET: CiQA4As1qzV4OXI+mIV0VfMnn/cio50eFmA5vs1n/Eukne29by0SQwASR2PRN3Z0oWxrR+g62EPKhG4F+2RjCuM/LTx4C4piWtORg43xoohhWli6wO5iBDQD8OTZyJOHXjdG2CNWoOGYci4=
    MYSQL_PASSWORD: CiQA4As1q2WTJDXPmd3hxzw+lY1cN+2cc6P9F9ZP1FnvwHI29YsSOQASR2PR87KdV60ZH+e4T0W/5BxKI/4IZB7aZWGANhJodI9Qk/dv+dblPNGz9ilBXMSgyMFxzkC6nA==
    MYSQL_USER: CiQA4As1q4tKL5jA5FHkFjMCdmcaFeBPAdhE8qaqLGfqVbTWnpsSLQASR2PRx3j4asgomn1WidvRIShLpmYseFlLkHp7yzDu8zRKg40VmfkfkDGFDw==
