version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14.2
    container_name: prisma
    environment_file:
      - .env.prisma.prod
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mysql
            port: 3306
            host: "${MYSQL_HOST}"
            user: "${MYSQL_USER}"
            password: "${MYSQL_PASSWORD}"
            migrations: true
