version: '3'
services:
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: '/cloud_sql_proxy -instances=${CLOUDSQL_CONNECTION}=tcp:0.0.0.0:3306 -credential_file=/config'
    ports:
      - 3306:3306
    volumes:
      - ./cloud-sql-credentials.json:/config
    restart: always
  prisma:
    image: prismagraphql/prisma:1.14.2
    container_name: prisma
    depends_on:
      - cloudsql-proxy
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mysql
            port: 3306
            host: "${MYSQL_HOST}"
            user: "${MYSQL_USER}"
            password: "${MYSQL_PASSWORD}"
            migrations: true
