cloudsql-proxy:
  container_name: cloudsql-proxy
  image: gcr.io/cloudsql-docker/gce-proxy:1.11
  command: "/cloud_sql_proxy -instances=${CLOUDSQL_CONNECTION}=tcp:0.0.0.0:3306 -credential_file=/config"
  ports:
    - 3306:3306
  volumes:
    - ../cloud-sql-credentials.json:/config
  restart: always
